### ISSUE TITLE
Not applicable to some(?) Initium Media articles

### ISSUE THREAD

**Issue by marc0cheung** [YS-Wong/Article-Unlocker#1]
An awesome article unlocking tool, but a bug was recently discovered in the process of using it, **not sure if it was a problem with the tool or the Initium Media website.** Or maybe there's something wrong with my personal preference settings.

When I used the tool to unlock Article 1, only the first three paragraphs of the article were displayed, while the rest of the article was not successfully unlocked (See [the Telegraph Version of Article #1](https://tinyurl.com/3zyu8mcc) for reference).

However, when I use the tool to unlock Article 2, the tool can achieve a complete full-text unlock.

Article 1: [How Hong Kong Indie Press in Difficulty](https://theinitium.com/article/20220722-culture-how-hk-indie-press-in-difficulty/)
Article 2: [Hong Kong COVID Health Code and RNR](https://theinitium.com/article/20220720-hongkong-covid-health-code-and-real-name-registration/)

![Article1](https://user-images.githubusercontent.com/88013550/180589305-d596068a-62ca-416a-b9ac-a70c1867d72d.png)

Article 1 (Telegraph Reference): [Link](https://tinyurl.com/3zyu8mcc)

**Comment by easonwong-de** [comment]
This add-on depends on the content generated by Telegram bot [Article reader|Статей читалка](https://t.me/chotamreaderbot). If an article hasn’t been unlocked with the bot or the bot failed to obtain the text, the add-on won’t work on the article. You can also use [Article reader|Статей читалка](https://t.me/chotamreaderbot) on Telegram to unlock articles when the add-on fails to unlock them, so that other users will be able to view the articles with the add-on ☺️
